opensearch-project/opensearch-go

.github/workflows/links.yml
=> Add link checker workflow

README.md
Update forum category to clients
=> Update forum category to clients

opensearch_example_test.go
Rename variable name to client.
=> Update variable name

.github/workflows/links.yml, README.md, USER_GUIDE.md
Include example as user guide similar to documentation website.
=> Add user guide

.github/workflows/dco.yml, CONTRIBUTING.md
* Include workflow to check commits are signed.
* Update url to absolute from relative.
#71 
=> Include dco workflow check and fix invalid url path

opensearchutil/bulk_indexer.go, opensearchutil/bulk_indexer_internal_test.go
Add version and routing fields, optimize the memory usage.
#68 
=> Updates to bulk indexer. 

.github/workflows/links.yml, USER_GUIDE.md
Add an example explaining how to perform authentication using IAMs. 
#75 
=> Add example for IAM authentication

.gitignore, .golangci.yml, Makefile
[golangci-lint](https://golangci-lint.run/) is a Go linters aggregator. It helps improve the code quality and prevents bugs. I'd recomede to integrate golangci-lint and then enable linter one by one.
There are many issues with formatting, misspellings and even potentially dangerous bugs.
=> golangci-lint integration

.github/workflows/backport.yml, .github/workflows/delete_backport_branch.yml, ADMINS.md, DEVELOPER_GUIDE.md, MAINTAINERS.md, README.md, USER_GUIDE.md
Adding auto backport functionality with auto delete for backport branches with documentation.
#100 
=> Add auto backport functionality

.github/workflows/test-compatibility.yml, COMPATIBILITY.md
Adding new OpenSearch versions and updating the compatibility matrix.
=> Adding new OpenSearch versions and updating compatibility matrix

.github/workflows/changelog_verifier.yml
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
Add changelog skiplabel on workflow with skip-changelog label
https://github.com/opensearch-project/opensearch-go/pull/208#issuecomment-1372838786
=> Add changelog skiplabel on workflow with skip-changelog label

CODEOWNERS, MAINTAINERS.md
Signed-off-by: dblock <dblock@amazon.com>
This syncs actual permission with CODEOWNERS.
I've emailed the fine folks in the maintainers list to add some new folks here and get this project going a bit, too.
=> Sync actual permissions and CODEOWNERS.

RELEASING.md
Adding release process documentation.
#144 
=> Adding branching and releasing documentation

UPGRADING.md
Improve the Upgrade.md for the new error handling.
https://github.com/opensearch-project/opensearch-go/pull/246#issuecomment-1481391595
=> Upgrade.md: Add before example for error handling

.github/workflows/dependabot_pr.yml
Add the dependency for prettier for the dependabot added by #297
=> Install prettier dependency in workflow for dependabot

USER_GUIDE.md, guides/data_streams.md
Linked user guides from USER_GUIDE.
Closes https://github.com/opensearch-project/opensearch-go/issues/279
=> Linked user guides from USER_GUIDE.

CHANGELOG.md, opensearchapi/api.document_test.go
_Add tests to check UpdateRequestByQuery request._
_Closes [#282]._ 
=> Add tests to check UpdateRequestByQuery request

CHANGELOG.md
=> Fixing Changelog with only unreleased entries

.github/workflows/test-compatibility.yml, CHANGELOG.md, COMPATIBILITY.md
Cleaning up changelog according to what was released and updating compatibility matrix.
=> Cleaning up changelog and updating documentation

.codecov.yml, .github/workflows/test-integration.yml, .github/workflows/test-unit.yml, CHANGELOG.md, Makefile
added code-coverage-comment.yml file to add a comment to each PR of code coverage
=> create code-coverage-comment.yml file to create a comment of code coverage

CHANGELOG.md, RELEASING.md, internal/version/version.go
Added changelog history
Update internal version
Related to https://github.com/opensearch-project/opensearch-go/issues/264
=> Bump version to v3.0.0

CHANGELOG.md, RELEASING.md, internal/version/version.go
Preparing for release, 3.1.0. There are new features, so incremented the second number.
=> Preparing for release, 3.1.0.

CHANGELOG.md, RELEASING.md, internal/version/version.go
Preparing for next developer iteration, 3.1.1.
Waiting on https://pkg.go.dev/github.com/opensearch-project/opensearch-go/v3
=> Preparing for next developer iteration, 3.1.1.

.github/workflows/lint.yml
=> github/workflow: fix npm prittier

.github/workflows/dependabot_pr.yml
=> Fixing prettier install in dependabot PR actions workflow

.github/workflows/dependabot_pr.yml
Bump action version of dependabot workflow
=> bump dependabot_pr action versions

CHANGELOG.md, internal/version/version.go
Preparing for next developer iteration, 4.0.1.
=> Preparing for next developer iteration, 4.0.1

.github/workflows/test-compatibility.yml, CHANGELOG.md
=> workflows: add OpenSearch 2.15 to compatibility workflow test

CHANGELOG.md, internal/version/version.go
Added changelog history
Update internal version
=> Bump version to 4.1.0

CHANGELOG.md, internal/version/version.go
=> Prepare for new development cycle

CHANGELOG.md, internal/version/version.go
- Adjust internal version to 4.2.0
- Replace Unreleased with 4.2.0 in CHANGELOG 
=> Bump version to 4.2.0

CHANGELOG.md, internal/version/version.go
- Add unrekeased section to CHANGELOG
- Adjust internal version
=> Preperations for next development cycle

CHANGELOG.md, plugins/ism/api_policies.go, plugins/ism/api_policies_test.go
- Add support for the alias action
=> plugins/ism: add alias action

CHANGELOG.md, internal/version/version.go
Preparing for next developer iteration, 4.4.1.
Closes https://github.com/opensearch-project/opensearch-go/issues/666.
=> Preparing for next developer iteration, 4.4.1.

.ci/opensearch/Dockerfile.opensearch
Fix current inregration tests ci issues
=> .ci/opensearch: fix launch OpenSearch ci errors

CHANGELOG.md, internal/version/version.go
Bump lib version to v4.5.0
Ref https://github.com/opensearch-project/opensearch-go/issues/702
=> Bump version to v4.5.0

CHANGELOG.md, internal/version/version.go
Preparing for next developer iteration
Closes #702 
=> Preparing for next developer iteration
