doc.go, opensearch.go, opensearch_internal_test.go
Accept OPENSEARCH_URL and ELASTICSEARCH_URL for backward compatibility, but not together.
#49
=> Accept OPENSEARCH_URL for address

README.md
Just adding the documentation badge pointing to the documentation on pkg.go.dev.
=> Add documentation badge to README.

.ci/opensearch/Dockerfile.opensearch
remove security plugin to disable security, since, just
adding disable true causes connection error.
=> Update opensearch docker file

.github/workflows/test-integration-unreleased.yml
Adding support to run integration tests against unreleased versions of OpenSearch. This will help in getting the client ready for the next OpenSearch release.
Part of #99  
=> Adding support to test against unreleased OpenSearch

.github/workflows/test-compatibility.yml, COMPATIBILITY.md, internal/version/version.go
* Bump client version to 2.0.0.
* Add OpenSearch 2.0 to test matrix.
#110 
=> Bump client version to 2.0 and add OpenSearch 2.0

USER_GUIDE.md
In the original example, no indexing was done and the variable is only used in fmt.Println(). This could be misleading to the user, so we have corrected it so that indexing is performed.
Closes #98
=> Update to do request of create index in USER_GUIDE

USER_GUIDE.md
Signed-off-by: Máté Lang <langmatelaszlo@gmail.com>
Add documentation about the recently added AWS SDK v2 request signer.
Fixes https://github.com/opensearch-project/opensearch-go/issues/129.
=> chore: user guide for aws sdk v2 signer

opensearchapi/api.create.go, opensearchapi/api.exists_source.go, opensearchapi/api.explain.go, opensearchapi/api.get_source.go, opensearchapi/api.termvectors.go, opensearchapi/api.update.go
Fixing url paths for some APIs after type removal. 
Closes #132 
=> Fixing paths for some APIs

.github/workflows/test-compatibility.yml, COMPATIBILITY.md, internal/build/go.mod, internal/version/version.go, opensearchapi/test/go.mod
Bumping client version to 2.0.1 and updating+simplifying the compatibility matrix.
=> Bumping client version to 2.0.1

.github/workflows/test-compatibility.yml, COMPATIBILITY.md, internal/build/go.mod, internal/version/version.go, opensearchapi/test/go.mod
* Bumping version to 2.0.1
* Updating and simplifying compatibility matrix
* Adding OpenSearch 2.1.0 to compatibility matrix
(cherry picked from commit 25a1a6f29b6f9977f655e7f369f29d8bbf04fe1b)
Backport #137 to 2.0
=> Bumping client version to 2.0.1 (#137)

USER_GUIDE.md
Single quotes are used in the json representing the index mapping, resulting in a parse error. Fix this.
```
[400 Bad Request] {"error":{"root_cause":[{"type":"parse_exception","reason":"Failed to parse content to map"}],"type":"parse_exception","reason":"Failed to parse content to map","caused_by":{"type":"json_parse_exception","reason":"Unexpected character (''' (code 39)): was expecting double-quote to start field name\n at [Source: (byte[])\"{\n\t    'settings': {\n\t        'index': {\n\t            'number_of_shards': 4\n\t        }\n\t    }\n\t}\"; line: 2, column: 7]"}},"status":400}
```
↓
```
[200 OK] {"acknowledged":true,"shards_acknowledged":true,"index":"go-test-index1"}
```
For minor modifications, the step of opening an Issue was omitted.
=> Fix json format of index mapping in USER_GUIDE

CHANGELOG.md, opensearchutil/bulk_indexer.go, opensearchutil/bulk_indexer_internal_test.go
Signed-off by: Kyle Darryl Aguilar <aguilarkyledarryl@gmail.com>
Renamed the sequence number struct tag to resolve issues when performing optimistic concurrency control
Resolves https://github.com/opensearch-project/opensearch-go/issues/165
=> Replaced if_seq_num to if_seq_no

.github/workflows/changelog_verifier.yml, .github/workflows/dependabot_pr.yml
Signed-off-by: Daniel (dB.) Doubrovkine <dblock@amazon.com>
Can't figure out why this action isn't doing anything for the dependabot PRs, let's start by upgrading it. Added skip-changelog label support too.
=> Upgrade to dependabot-changelog-helper@v2.

.github/CODEOWNERS, MAINTAINERS.md
Adding @dblock to maintainers. Moving @jmazanec15 and @vamshin to Emeritus. 
=> Add and update maintainers

CHANGELOG.md, opensearchutil/bulk_indexer.go, opensearchutil/bulk_indexer_internal_test.go
Bug fix.
Adjust to set `retry_on_conflict` when using bulk indexer.
=> bugfix: adjusts to use retry_on_conflict on bulk

CHANGELOG.md, internal/build/go.mod, internal/version/version.go, opensearch.go, opensearch_internal_test.go, opensearchapi/test/go.mod
Removing the version check before performing every request.
Also increments to next version.
Part of https://github.com/opensearch-project/opensearch-go/pull/216#pullrequestreview-1262798295
=> Removing info call before performing requests

CHANGELOG.md, USER_GUIDE.md, signer/awsv2/sdkv2signer.go, signer/awsv2/sdkv2signer_test.go
Adding support and examples for AOSS.
#204 
=> Adding support and examples for AOSS

CHANGELOG.md, USER_GUIDE.md, signer/aws/aws.go, signer/aws/aws_test.go
Like https://github.com/opensearch-project/opensearch-go/pull/216 but for the v1 signer.
- Updated SDK v1 signer
- Updated user guide
- Updated changelog
I did not open one but could if needed. Originally tried solving it via https://github.com/aws/aws-sdk-go/pull/4761 but this way is more "right".
=> Update signer v1 example for AOSS

CHANGELOG.md, opensearchapi/api._.go, opensearchapi/api.info.go, opensearchapi/api.pointintime.create.go, opensearchapi/api.pointintime.delete.go, opensearchapi/api.pointintime.get.go, opensearchapi/opensearchapi_integration_test.go
Add  the Point in Time API.
https://opensearch.org/docs/latest/search-plugins/point-in-time-api/
Closes #251 
=> Add point in time api

CHANGELOG.md, opensearchutil/bulk_indexer_integration_test.go
This change shows, that client supports functionality of upsert in update action.
For this, the source code of the integration tests was refactored.
Closes [#207](https://github.com/opensearch-project/opensearch-go/issues/207)
=> Add testcases to check upsert functionality

CHANGELOG.md, MAINTAINERS.md
The project maintainers are inviting @Jakob3xD to opensearch-go maintainers, and they kindly accepted.
Jacob just diligently worked through two significantly complex changes in the client, both breaking backwards compatibility. I think his code quality is very high, I really appreciate his patience, too.
- https://github.com/opensearch-project/opensearch-go/pull/246
- https://github.com/opensearch-project/opensearch-go/pull/237
- https://github.com/opensearch-project/opensearch-go/pull/253
I'm moving @svencowart to emeritus, have not been able to reach them.
Sorted names alphabetically, formatted markdown.
For more information on following Developer Certificate of Origin and …
=> Added @Jakob3xD as a co-maintainer.

.github/CODEOWNERS
My bad for forgetting CODEOWNERS in #270.
I've adjusted @Jakob3xD's permissions level to "maintain". You can approve this PR! :)
=> Added Jakob3xD to CODEOWNERS, removed @svencowart.

CHANGELOG.md, opensearchapi/opensearchapi.error.go, opensearchapi/opensearchapi.response.go, opensearchapi/opensearchapi_response_internal_test.go
- Check if parsed error is empty
- Improve error string output
- Adds test for errors without an error response body
Closes https://github.com/opensearch-project/opensearch-go/issues/281
=> opensearchapi: Fix handling of errors without error response body

.github/workflows/dependabot_pr.yml
Dependabot PRs add a Changelog line which fails the recent prettier check. See https://github.com/opensearch-project/opensearch-go/actions/runs/4662363358/jobs/8252624135?pr=294
This PR adds a prettier formatting in the dependabot PR workflow.
=> Add prettier formatting to dependabot prs

DEVELOPER_GUIDE.md
I added guidelines for Windows developers in the Developer Guide (to use WSL2 and how to use WSL)
[#308 ]
=> [BUG] Windows compatibility with Makefile #308

CHANGELOG.md, opensearchtransport/opensearchtransport.go, opensearchtransport/opensearchtransport_integration_test.go
With this change the http reponse body gets automatically closed by us so the user don't have to do it and it prevents unclosed connections if the user forgot to close it. This wont brake any existing implementations as you can still call `.Close()` on the Body.
https://pkg.go.dev/net/http#Client.Do
> If the returned error is nil, the Response will contain a non-nil Body which the user is expected to close. If the Body is not both read to EOF and closed, the Client's underlying RoundTripper (typically Transport) may not be able to re-use a persistent TCP connection to the server for a subsequent "keep-alive" request. 
For more information on following Developer Certificate of …
=> Read, close and replace the http Reponse Body

.ci/opensearch/Dockerfile.opensearch, .ci/opensearch/docker-compose.yml, .github/workflows/test-compatibility.yml, CHANGELOG.md, Makefile
- Add a healthcheck to the docker container that kills it self, forcing it to restart the container
- Add a bash for loop to wait for the cluster to be ready
Closes #296 
=> [Feature] Add healthcheck to docker container

CHANGELOG.md, internal/build/go.mod, internal/version/version.go, opensearchapi/test/go.mod
* Bumps client version to 2.3.0.
* Cleaning up changelog.
=> Bump client version to 2.3.0

.github/workflows/lint.yml, .golangci.yml, CHANGELOG.md
_This PR adds option to check overall quality of code._
_Closes [#307]._ 
=> [FEATURE] Code analysis tool

USER_GUIDE.md
There is a common case where a structure is used in the Body of an API request, which requires conversion to io.Reader. There is a useful utility function available for this use case, but it is not often noticed, so it is included in the user guide.
ref. https://github.com/opensearch-project/opensearch-go/issues/331#issuecomment-1608111897
There is no Issue to be resolved, but the related Issue is https://github.com/opensearch-project/opensearch-go/issues/331
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origi …
=> Add an introduction to utility function NewJSONReader in USER_GUIDE

.github/workflows/test-compatibility.yml
Add opensearch 2.6.0, 2.7.0, 2.8.0 to compatibility test
=> Add opensearch 2.6.0, 2.7.0, 2.8.0 to compatibility test

CHANGELOG.md, go.mod, go.sum, opensearchapi/api.indices.datastream_test.go, opensearchapi/api.indices.get_datastream_stats.go, opensearchapi/api.indices.get_datastream_stats_test.go
This makes the GetDataStreamStats request only add the `Name` and path separator (`/`) to the path if Name is not empty.
As it stands when using this function without setting a name the path will be:
```
/_data_stream//_stats
```
This path is then used by the AWS Signer to calculate a signature. When the request is sent the server recalculates the signature but the additional `/` has been dropped by now and we get a signature mismatch. See #337 for details.
I have tested this fix in our own codebase and it resolves the issue as described.
Closes #337 
For more information on following Developer Certificate of Origin and signing off your commits, please check …
=> Data stream stats: Add name only if present

CHANGELOG.md, opensearchtransport/connection.go, opensearchtransport/connection_benchmark_test.go, opensearchtransport/connection_integration_test.go, opensearchtransport/connection_internal_test.go, opensearchtransport/discovery.go, opensearchtransport/discovery_internal_test.go, opensearchtransport/doc.go, opensearchtransport/logger.go, opensearchtransport/logger_benchmark_test.go, opensearchtransport/logger_internal_test.go, opensearchtransport/metrics.go, opensearchtransport/metrics_internal_test.go, opensearchtransport/opensearchtransport.go, opensearchtransport/opensearchtransport_benchmark_test.go, opensearchtransport/opensearchtransport_integration_multinode_test.go, opensearchtransport/opensearchtransport_integration_test.go, opensearchtransport/opensearchtransport_internal_test.go
Once #352 is merged I'll rebase this MR.
Update golangci-lint config and bump its version.
Solve linting complains inside opensearchtransport folder.
This is a side product of my current refactoring. I fixed all linting complains in my feature branch and I want to merge some of those fixes upstream to reduce the files changed by my feature branch.
There is not open issue for linting.
=> golangci-lint: Solve Complains for opensearchtransport

CHANGELOG.md, DEVELOPER_GUIDE.md
This helps new contributors and users of the go client to start testing and using the go client by including the docker commands to start a docker container locally. 
=> tannerjones4075- update developer guide

CHANGELOG.md, guides/search.md, opensearchapi/api.get_source.go, opensearchapi/opensearchapi_integration_test.go
Source parameter in GetSourceRequest is not correctly defined. Fixing that and adding tests and samples for the GetSource API.
Fixes #283 
=> Fixing GetSourceRequest

.github/workflows/test-compatibility.yml, CHANGELOG.md, COMPATIBILITY.md, guides/search.md, opensearchapi/api.get_source.go, opensearchapi/opensearchapi_integration_test.go
Backporting #402 and #401 to 2.x
=> [Backport 2.x] Fixing GetSourceRequest

.github/workflows/govulncheck.yml, CHANGELOG.md
Signed-off-by: Tanner Jones <alltechguyblog@gmail.com>
=> Added govulncheck workflow

CHANGELOG.md, _samples/README.md, _samples/advanced_index_actions.go, _samples/bulk.go, _samples/data_stream.go, _samples/document_lifecycle.go, _samples/index_lifecycle.go, _samples/json.go, _samples/search.go, guides/json.md
=> Adding a guide for making raw json requests using the client

CHANGELOG.md, DEVELOPER_GUIDE.md
Corrects developer guide with current go 1.20 in summary.
=> developer-guide: corrects go version in summary

CHANGELOG.md, RELEASING.md, internal/version/version.go
- Increments to next developer iteration.
- Updates CHANGELOG with Unreleased.
- Updates RELEASING with info about how to do this.
Note that the first time we take a pull request with a new feature we should be asking the requester to change the version to 3.1.0.
Closes #264.
=> Preparing for next developer iteration, 3.0.1.

CHANGELOG.md, opensearchtransport/discovery.go, opensearchtransport/discovery_internal_test.go, opensearchtransport/testdata/nodes.info.json
When using the opensearch-go library to access an opensearch cluster deployed with IPV6, an access error will occur when calling other APIs after calling the DiscoverNodes method.
[_List any issues this PR will resolve, e.g. Closes [...]._ ](https://github.com/opensearch-project/opensearch-go/issues/458)
=> fix:Clusters deployed using IPV6 do not support the DiscoverNodes method

CHANGELOG.md
Change the changelog version back to `Unreleased` as the verify-changelog job matches on the regexp `Version Pattern: ^## \[((v|V)?\d*\.\d*\.\d*-?\w*|unreleased|Unreleased|UNRELEASED)\]`.
=> changelog: changed unreleased version back for Dependabot PR to work

.ci/opensearch/Dockerfile.opensearch, .ci/opensearch/docker-compose.yml, .github/workflows/test-compatibility.yml, .github/workflows/test-integration.yml, CHANGELOG.md, guides/index_lifecycle.md, opensearch_secure_integration_test.go
Remove references to the default credentials of admin:admin and changes the CI according to default admin credentials changes for the 2.12.0 release.
=> Remove references to the default credentials of admin:admin

CHANGELOG.md, opensearchapi/api_nodes-info.go
Can be after https://github.com/opensearch-project/OpenSearch/pull/12543 is merged.
=> opensearchapi: revert node info OpensearchVersion type change

CHANGELOG.md, signer/aws/aws.go, signer/aws/aws_test.go
The empty body SHA is different (incorrect, it's the SHA for "hello") in the SDK v1 code, it should be one of an empty string.
It's correct in V2, https://github.com/opensearch-project/opensearch-go/blob/d38bdc15de7a759e3c1c538d173a63eef45a2dd2/signer/awsv2/sdkv2signer.go#L33C23-L33C87. 
Closes #492.
=> Fix: empty body SHA is incorrect using AWS SDK v1 signer.

.github/workflows/test-compatibility.yml, CHANGELOG.md, Makefile, guides/index_lifecycle.md, opensearchapi/api_nodes-stats.go
- Adds missing struct
- tests against opensearch 2.13
- change docker compose to v2
https://github.com/actions/runner-images/issues/9557
Closes #505 
=> Use docker compose v2, add nodes stats global io usage struct, tests against opesnearch 2.13

CHANGELOG.md, opensearchapi/api_search.go, opensearchapi/api_search_test.go
Previously, calling the `Search` function [here](https://github.com/opensearch-project/opensearch-go/blob/e0278abbe00fb090faba23170d2a1aac491d6d22/opensearchapi/api_search.go#L21) with `Explain` set to true in `Params` in the `SearchReq` did **not** add an explanation payload to each document. This pull request fixes that by adding an `Explanation` field to the `SearchHit` struct.
This resolves issue [503](https://github.com/opensearch-project/opensearch-go/issues/503),  which I raised.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#de …
=> Add the Explanation field containing the document explain details to SearchHit

CHANGELOG.md, opensearchapi/api_search.go, opensearchapi/api_search_test.go
Add missing `/ ` for search requests when not searching specific indices.
Closes https://github.com/opensearch-project/opensearch-go/issues/470
=> Fix search request missing a slash when no indices are given

CHANGELOG.md, error.go, error_test.go
Add test for 429 example response. Handle the error with an added sentinel.
=> Fixes opensearch-project/opensearch-go#522

CHANGELOG.md, opensearchapi/api_document-get.go, opensearchapi/api_document_test.go
Add `fields` to document get response to support `stored_fields` param
To support getting document with `stored_fields` param
```
PUT /my-index
{
"mappings": {
"properties": {
"demo": {
"type" : "keyword",
"store": true
}
}
}
}
```
```
GET /my-index/_doc/1?stored_fields=foo-stored
```
```
{
"_index": "my-index",
"_id": "1",
"_version": 1,
"_seq_no": 0,
"_primary_term": 1,
"found": true,
"fields": {
"foo-stored": [
"bar"
]
}
}
```
=> Add fields to document get response to support stored_fields param

.ci/opensearch/docker-compose.yml, .github/workflows/test-integration-unreleased.yml, CHANGELOG.md, Makefile, opensearchapi/api_nodes-stats.go, opensearchapi/api_scroll_test.go, plugins/ism/api.go, plugins/ism/api_add.go, plugins/ism/api_change.go, plugins/ism/api_explain-params.go, plugins/ism/api_explain.go, plugins/ism/api_policies-delete.go, plugins/ism/api_policies-get.go, plugins/ism/api_policies-put-params.go, plugins/ism/api_policies-put.go, plugins/ism/api_policies.go, plugins/ism/api_policies_test.go, plugins/ism/api_remove.go, plugins/ism/api_retry.go, plugins/ism/api_test.go, plugins/ism/inspect.go, plugins/ism/internal/test/helper.go
- add ISM Policy
Closes https://github.com/opensearch-project/opensearch-go/issues/74
=> Add ISM Policy

CHANGELOG.md, opensearchapi/api_search-params.go, opensearchapi/api_search-params_test.go
Added `search_pipeline` field in SearchParams struct.
_Note: I didn't add any tests as I can't see any others there for existing `SearchParam` fields._
With the addition of hybrid search and search pipelines in Opensearch version `2.11`, a new `search_pipeline` parameter exists on the `_search` endpoint ([docs here](https://opensearch.org/docs/latest/search-plugins/search-pipelines/using-search-pipeline/)).
This pull request supports the new search pipelines functionality by allowing users of the library to set the `search_pipeline` parameter via the `SearchParams` struct.
For more information on following Developer Certificate of Origin and signing off your commits, please …
=> Add missing `search_pipeline` field in `opensearchapi.SearchParams`

CHANGELOG.md, opensearchtransport/opensearchtransport.go, opensearchtransport/opensearchtransport_internal_test.go
Make the transport use a new reader for each retry when gzip compression is enabled.
Also be more explicit about doing so for non-compressed requests.
Test included.
Closes #541.
=> Fix empty request body on retries with compression enabled

CHANGELOG.md, plugins/ism/api_policies.go, plugins/ism/api_test.go
Closes https://github.com/opensearch-project/opensearch-go/issues/555
=> Fix ISM Plugin Transitions Conditions struct (#555)

CHANGELOG.md, internal/test/helper.go, opensearchapi/api_indices-mapping.go, opensearchapi/api_indices.go, opensearchapi/api_nodes-stats.go, plugins/security/api_actiongroups.go, plugins/security/api_internalusers.go, plugins/security/api_roles-get.go, plugins/security/api_roles-put.go, plugins/security/api_roles.go, plugins/security/api_rolesmapping.go, plugins/security/api_tenants.go
- Fix FLS role type
- Fix json compare when response is null
- Fix function where the wrong var is given to parse the response
- Add missing node stats cache field 
Closes https://github.com/opensearch-project/opensearch-go/issues/560 
=> Field, Function and test fixes, adding missing struct to node stats

CHANGELOG.md, USER_GUIDE.md, guides/retry_backoff.md, opensearchtransport/opensearchtransport.go, opensearchtransport/opensearchtransport_internal_test.go
=> fix request context cancellation is ignored when retryBackoff (#539)

CHANGELOG.md, UPGRADING.md, error.go, error_test.go
In ParseError, when json response from server is unknown, it used to return a string response (`*fmt.wrapError`). This is now changed to return a StringError struct (`*opensearch.StringError`).  
Closes #582
=> Improves ParseError response when server response is an unknown json

.github/workflows/test-compatibility.yml, .github/workflows/test-integration-unreleased.yml, internal/test/helper.go, opensearchapi/api_cat_test.go, opensearchapi/api_cluster_test.go, opensearchapi/api_script_test.go, plugins/ism/api_test.go, plugins/security/api_ssl_test.go
Similar to https://github.com/opensearch-project/opensearch-py/pull/798, needs a different JDK depending on branch.
=> Fix: integration tests with unreleased version of OpenSearch.

CHANGELOG.md, opensearchapi/api_search.go, opensearchapi/api_search_test.go
Adding the `Explanation` field to the 
Closes issue [#601](https://github.com/opensearch-project/opensearch-go/issues/601) 
=> Add the Suggest field to the SearchResp struct

CHANGELOG.md, opensearchapi/api_snapshot-get.go
Split the SnapshotGetResp into more sub structs so they can be reused by the user.
This is for example needed when looping over `SnapshotGetResp.Snapshots` and want to give the struct to a function.
This is actually a more general issue affecting more structs that could be solved by code generation in the future.
None
=> opensearchapi: split SnapshotGetResp into sub structs

CHANGELOG.md, opensearchapi/api_scroll-get.go
Add MaxScore field to ScrollGetResp
https://github.com/opensearch-project/opensearch-go/actions/runs/10579861232/job/29313341627?pr=606#step:7:993
=> opensearchapi: add MaxScore field to ScrollGetResp

CHANGELOG.md, plugins/ism/api_policies.go, plugins/ism/api_policies_test.go
- Fix ISM Transition to omitempty Conditions field
- Fix ISM Allocation field types
Closes #591 
=> Fix ISM issues

CHANGELOG.md, plugins/ism/api_policies.go, plugins/ism/api_policies_test.go, plugins/ism/api_test.go
- Fix error notification types by making them pointers and adding omitempty
- Add test for channel
- Add missing struct for Channel field
=> plugins/ism: Fix error notification types

CHANGELOG.md, opensearchtransport/opensearchtransport.go, opensearchtransport/opensearchtransport_internal_test.go
When retrying, the body can be drained, and there is already code that resets the request body on retries. The issue was that we were sending the drained request to the signer before reseting the request body, so signature would be based on an empty body
#202 
=> Fix signer receiving a drained body on retries

CHANGELOG.md, opensearchutil/bulk_indexer.go, opensearchutil/bulk_indexer_internal_test.go
Execute all bulk item failure callbacks (if they exist) in worker's buffer when a bulk request fails.
Fixes https://github.com/opensearch-project/opensearch-go/issues/626
=> Execute item failure callback execution on bulk request error

CHANGELOG.md, internal/version/version.go
Part of https://github.com/opensearch-project/opensearch-go/issues/628. 
=> Prepare for release, 4.3.0.

CHANGELOG.md, Makefile, opensearchapi/api_nodes-stats.go, opensearchapi/api_search-template.go, opensearchapi/api_search.go, opensearchapi/api_search_test.go
For queries specifying [highlights](https://opensearch.org/docs/latest/search-plugins/searching-data/highlight/), the the `SearchHit`s on the `SearchResp` now include the highlight information returned in the api response.
Closes https://github.com/opensearch-project/opensearch-go/issues/653
=> Add Highlight field to SearchHit struct

.github/workflows/test-integration-unreleased.yml, CHANGELOG.md, opensearchapi/api_search.go, opensearchapi/api_search_test.go
Added MatchedQueries field in response struct of SearchHit.
This is done to add support for receiving matched queries in response when using `_name` with query clauses
_List any issues this PR will resolve, e.g. Closes [opensearch-project/opensearch-go/issues/573]._ 
=> Adds MatchedQueries field to SearchHit

.github/workflows/test-compatibility.yml, CHANGELOG.md, opensearchapi/api_cluster-stats.go, opensearchapi/api_indices-stats.go, opensearchapi/api_nodes-info.go, opensearchapi/api_nodes-stats.go
Adds the newly added fields. IDK if all the types are correct, as they are not documented in the open API spec.
Closes #668 
=> add support for opensearch 2.19

.github/workflows/test-integration.yml
Lock version of OpenSearch for integration tests. When 2.19 was released it broke CI, which is not desirable. With this change we have to upgrade deliberately like we do for integration tests already.
=> Lock version of OpenSearch for integration tests.

CHANGELOG.md, internal/version/version.go
Preparing for release, 4.4.0. We have new features, so bumped from 4.3.1 to 4.4.0.
Part of https://github.com/opensearch-project/opensearch-go/issues/666.
=> Preparing for release, 4.4.0.

CHANGELOG.md, opensearchapi/api_search.go, opensearchapi/api_search_test.go
Added [inner hits param](https://opensearch.org/docs/latest/search-plugins/searching-data/inner-hits/) support
=> Inner hits support

CHANGELOG.md, go.mod, opensearchapi/api_cat-recovery.go
Bump Golang to version 1.22 because it is the oldest maintaned Golang version.
This also fixed the CI for dependency PR's.
=> Bump golang version to 1.22

CHANGELOG.md, opensearchapi/api_msearch.go, opensearchapi/api_msearch_test.go
Added Aggregations field in response struct of MSearchResp.
This is done to add support for receiving aggregations in msearch responses
=> Adds Aggregations field to MSearchResp

CHANGELOG.md, USER_GUIDE.md
correct usage of fmt.Printf for formatted output in code examples
None
=> docs(USER_GUIDE.md): correct usage of fmt.Printf for formatted output in code examples

CHANGELOG.md, error.go, error_test.go
We are observing conditions where Opensearch returns with an emtpy body. In that case, the error string returned is just blank which is very confusing to the end user.
To fix this, we add some more context to the error string to make it clear.
=> Improve error response when body is an empty string

CHANGELOG.md, opensearchapi/api_search.go, opensearchapi/api_search_test.go
`SearchResp` had the `Suggest` field but the `Options ` did not contain all the fields. The previous [PR ](https://github.com/opensearch-project/opensearch-go/pull/602) only covers the response from term suggesters. This change will cover all the fields in response for [term](https://docs.opensearch.org/docs/latest/search-plugins/searching-data/did-you-mean/) or [completion](https://docs.opensearch.org/docs/latest/search-plugins/searching-data/autocomplete/#completion-suggester) suggesters. 
Closes - https://github.com/opensearch-project/opensearch-go/issues/712 
For more information on following Developer Certificate of Origin and signing off your commits, please check …
=> Update SuggestOptions in the SearchResp struct to include all the fields for suggesters 

CHANGELOG.md, opensearchtransport/opensearchtransport_internal_test.go, signer/aws/aws.go, signer/aws/aws_test.go, signer/awsv2/sdkv2signer.go, signer/awsv2/sdkv2signer_test.go, signer/signer.go
Use a safe way to not directly manipulate host/port. Followed the same method the opensearch-py was using to override the signing port.
Closes #370 
=> Allow users to override signing port

CHANGELOG.md, opensearchapi/api_search-params.go, opensearchapi/api_search-params_test.go, opensearchapi/api_search.go, opensearchapi/api_search_test.go
The change is to add the `phase_took` feature in Search API start from OpenSearch 2.12
Example
```json
GET /my-index-000001/_search?phase_took
{
"took" : 105,
"phase_took" : {
"dfs_pre_query" : 0,
"query" : 69,
"fetch" : 22,
"dfs_query" : 0,
"expand" : 4,
"can_match" : 0
},
"timed_out" : false,
"_shards" : {
"total" : 5,
"successful" : 5,
"skipped" : 0,
"failed" : 0
},
"hits" : {
"total" : {
"value" : 0,
"relation" : "eq"
},
"max_score" : null,
"hits" : [ ]
}
```
Reference: 
* https://opensearch.org/blog/using-search-latency-monitoring/
* https://docs.opensearch.org/latest/api-reference/search-apis/search/
For more information on following Developer Certificate of Origin and …
=> Add phase_took feature to Search API
